version: "3.9"

services:

  bot:
    container_name: bot
    build: ./
    ports:
      - "50:50"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/bot
    depends_on:
      - bot-db
    command: ["healthy-check.sh", "bot-db:5433"]


  bot-db:
    container_name: bot-db
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
